name: Run Indeed Selenium Spider

on:
  workflow_dispatch:        # allows manual run from GitHub
  schedule:
    - cron: '0 12 * * *'    # optional: run every day at 12:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          python -m pip install --upgrade pip
          pip install -r indeed_scraper/requirements.txt

      - name: Run Selenium spider
        working-directory: indeed_scraper
        run: scrapy crawl indeed_selenium -o ../indeed_jobs_selenium.csv

      - name: Upload output CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: indeed_jobs_selenium
          path: indeed_jobs_selenium.csv
